# Generated by Django 2.2.3 on 2019-08-01 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190729_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='nums',
            new_name='goods_num',
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='trade.OrderInfo', verbose_name='订单信息'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_sn',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', '成功'), ('TRADE_CLOSED', '超时关闭'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_FINISHED', '交易结束'), ('paying', '待支付')], default='paying', max_length=10, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='signer_mobile',
            field=models.CharField(default='', max_length=11, verbose_name='联系电话'),
        ),
    ]
